#! /bin/bash
#
# This entrypoint script will be called everytime a container is started.
#
# Author: Kaj Munhoz Arfvidsson

set -e

# Set ROS_IP etc. for e.g. rviz remote connection
# https://stackoverflow.com/a/65912397
remote_ros() { source util/remote_ros.sh; }; remote_ros

# Install any dependencies that has been added by volume...

if [ -f requirements.txt ]; then
    # https://pip.pypa.io/en/stable/reference/requirement-specifiers/
    echo "# python -m pip install -r requirements.txt"
    python -m pip install -r requirements.txt
    echo "# python3 -m pip install -r requirements.txt"
    python3 -m pip install -r requirements.txt
fi

rosdep install \
    --rosdistro melodic \
    --from-paths src \
    --ignore-src \
    -q -r -y \

# To build anything that has been added by volume...
catkin build

# https://github.com/osrf/docker_images/issues/114
SETUP=$PWD/devel/setup.bash
source "$SETUP"
printf "\nsource '$SETUP'" >> $HOME/.bashrc


# Special for this project

source util/fix-python.sh

if [ -z $(which node) ]; then
    curl https://deb.nodesource.com/setup_16.x | bash
    apt-get install -y nodejs
    npm install --global yarn
    (cd src/ros_abconnect/streamer ; yarn install)
fi

exec "$@"

