#! /bin/sh
#
# Create a container from an image
#
# The last argument to the script is the image name, this will also be the
# container name after it has been created. The container is will be privileged
# and share the host network.
#
# OBS: This is the development version. The container will not be privileged
# or have access to the host's network.
#
# Author: Kaj Munhoz Arfvidsson


. "$(dirname "$0")/config.sh"


# Setting default arguments
if [ -z "$*" ]
then set -- "$IMAGE_TAG"
fi

# Build command
cmd="docker create"
cmd="$cmd -it"
cmd="$cmd -e TERM=xterm-256color"
cmd="$cmd -v $REPOSITORY_PATH/src:$WORKSPACE/src"
cmd="$cmd --name $CONTAINER_NAME"
cmd="$cmd $*"

if [ "$UTIL_DEBUG" ]; then
    echo "# Executing..."
    echo "$cmd"
fi

exec "$cmd"
