
STATE_STARTUP = 'STARTUP_S'
STATE_STANDBY = 'STANDBY_S'
STATE_READY = 'READY_S'
STATE_RUNNING = 'RUNNING_S'
STATE_FINISHED = 'FINISHED_S'
STATE_TRANSACK = 'TRANSACK_S'

# externally triggered
TRANS_NONE = 'NONE_T'
TRANS_SETUP = 'SETUP_T'
TRANS_START = 'START_T'
TRANS_STOP = 'STOP_T'

# internally triggered
TRANS_INIT = 'INIT_T'
TRANS_DONE = 'DONE_T'

LOG_FIELD_SEP = ','
LOG_ENTRY_SEP = ';'

