#! /bin/sh
#
# Create a container from an image
#
# The last argument to the script is the image name, this will also be the
# container name after it has been created. The container is will be privileged
# and share the host network.
#
# Author: Kaj Munhoz Arfvidsson


. "$(dirname "$0")/config.sh"


# Setting default arguments
if [ -z "$*" ]
then set -- "$IMAGE_TAG"
fi

[ "$(hostname)" = "svea2" ] && DEMONAME=obs
[ "$(hostname)" = "svea3" ] && DEMONAME=ego
[ "$(hostname)" = "svea7" ] && DEMONAME=onc

# Build command
cmd="docker create"
cmd="$cmd -it"
cmd="$cmd -e TERM=xterm-256color"
[ -n "$DEMONAME" ] && cmd="$cmd -e DEMONAME=$DEMONAME"
cmd="$cmd -v /dev:/dev"
cmd="$cmd -v $REPOSITORY_PATH:$WORKSPACE/src/$REPOSITORY_NAME"
cmd="$cmd --network host"
cmd="$cmd --privileged"
cmd="$cmd --name $CONTAINER_NAME"
cmd="$cmd $*"

if [ "$UTIL_BUILD" ]; then
    echo "# Executing..."
    echo "$cmd"
fi

exec $cmd
