#! /bin/sh
#
# Remove a container
#
# Author: Kaj Munhoz Arfvidsson


. "$(dirname "$0")/config.sh"


if [ -z "$*" ]
then set -- "$CONTAINER_NAME"
fi

# Build command
cmd="docker rm $*"

if [ "$UTIL_DEBUG" ]; then
    echo "# Executing..."
    echo "$cmd"
fi

exec $cmd
